### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by elemaster** [wechat-python-sdk/wechat-python-sdk#39]
我的是python3 用pip安装提示 求解
Collecting wechat-sdk
  Using cached wechat-sdk-0.5.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\n3292\AppData\Local\Temp\pip-build-yyhw7zno\wechat-sdk\setup.py", line 11, in <module>
        long_description=open("README.rst").read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 2: illegal multibyte sequence

**Comment by xrlin** [comment]
我也遇到同样的情况，请问你解决了吗？

**Comment by hbrls** [comment]
Windows 下开发各种痛苦，换吧

**Comment by JohnnyZhao** [comment]
如果目前对于 win 的开发环境依赖不大，建议尽快换 linux，在 win 下开发的坑多不多我不知道，到遇到坑没人帮你解决是真的，因为用 win 的开发者太少了。

**Comment by hbrls** [comment]
补充说明一下，并不是只这个库的坑，而是说各方面的坑，甚至不限于编程方面的

**Comment by su27** [comment]
win的编解码问题。见这个帖子： https://www.v2ex.com/t/98936
实在要用win的话，就用mingw/cygwin/虚拟机吧，不要在win下裸用Python。

**Comment by xrlin** [comment]
windows下开发确实有些坑，我一般是在linux下开发，但由于这次需要依赖windows环境就只能在windows下进行开发。
