### ISSUE TITLE
获取fakeid

### ISSUE THREAD

**Issue by xrlin** [wechat-python-sdk/wechat-python-sdk#42]
能否在用户刚关注公众号时及时获取到其fakeid？

**Comment by JohnnyZhao** [comment]
fakeid？指的是 openid 吗？

**Comment by xrlin** [comment]
@JohnnyZhao 主动向用户发送消息需要用到fakeid， fakeid和openid一般是不一样的，我想在用户刚关注时便将其openid和fakeid对应，然后将直接用户和与fakeid绑定，避免通过get_message_list()方法查找fakeid，增加效率。

**Comment by JohnnyZhao** [comment]
你说的是 unionid 吗？主动给用户发消息就是直接指定 openid 就可以了啊？如果你指的是你有多个微信公众号，需要辨别唯一用户的话，那 unionid 机制可以满足你的需求。

**Comment by JohnnyZhao** [comment]
微信的 unionid 机制可以参考这个文档：http://mp.weixin.qq.com/wiki/1/8a5ce6257f1d3b2afb20f83e72b72ce9.html

**Comment by doraemonext** [comment]
fakeid只能在用户发送消息时获取。

**PS：因为微信官方公众平台的功能已经愈加完善，WechatExt已经没有继续维护的必要，v0.6.0版本已经停止了对其的更新，推荐您使用官方接口WechatBasic进行开发。**

**Comment by xrlin** [comment]
@doraemonext  嗯，后来我通过微信服务号提供的功能实现了类似功能，感谢你提供简便的weixin开发接口^-^。
