### ISSUE TITLE
wechat_sdk.exceptions.NeedLoginError: {"base_resp":{"ret":200002,"err_msg":"invalid args"}}

### ISSUE THREAD

**Issue by btmanm** [wechat-python-sdk/wechat-python-sdk#48]
```PYTHON
from wechat_sdk import WechatExt

wechat = WechatExt(username='USERNAME', password='PASSWORD', ifencodepwd=True)
wechat.send_message('FAKEID', 'text')
```

> Traceback (most recent call last):
>   File "test_sendmessage.py", line 4, in <module>
>     wechat.send_message('FAKEID', 'text')
>   File "C:\z\wechat_sdk\ext.py", line 165, in send_message
>     raise NeedLoginError(r.text)
> wechat_sdk.exceptions.NeedLoginError: {"base_resp":{"ret":200002,"err_msg":"invalid args"}}

**Comment by doraemonext** [comment]
出现这种情况一般是由于您的 fakeid 非法。

**PS：因为微信官方公众平台的功能已经愈加完善，WechatExt已经没有继续维护的必要，v0.6.0版本已经停止了对其的更新，推荐您使用官方接口WechatBasic进行开发。**
