### ISSUE TITLE
最近开放的个性化菜单有考虑增加吗0.0

### ISSUE THREAD

**Issue by zhufree** [wechat-python-sdk/wechat-python-sdk#51]
>为了帮助公众号实现灵活的业务运营，微信公众平台新增了个性化菜单接口，开发者可以通过该接口，让公众号的不同用户群体看到不一样的自定义菜单。该接口开放给已认证订阅号和已认证服务号。

http://mp.weixin.qq.com/wiki/0/c48ccd12b69ae023159b4bfaa7c39c20.html

**Comment by zhufree** [comment]
看到README里面说不支持了0.0

**Comment by JohnnyZhao** [comment]
嗯，这个有时间加一下
