### ISSUE TITLE
建议 support 2/3 后 release 一个新版本

### ISSUE THREAD

**Issue by TennyZhuang** [wechat-python-sdk/wechat-python-sdk#55]
现在 如果用 `pip3 install wechat-sdk` 的话获取的 v0.5.9 会有来自 StringIO 的 ImportError，看了一下源码发现已经修复了，希望 release 一下，方便直接通过包管理器安装

**Comment by hbrls** [comment]
目前用 3 除了这个还有不少坑，建议直接从源码安装，然后我们一起来完善它

**Comment by JohnnyZhao** [comment]
嗯，稍后更新个 release，后续有时间会在 python 3 下全面测试一下。有愿意测试的同学我可以提供有所有认证权限的公众号用于测试。

**Comment by hbrls** [comment]
@JohnnyZhao 你是微信团队的么

**Comment by doraemonext** [comment]
已经 release。
