### ISSUE TITLE
Raise Not Login Error When Send Message 

### ISSUE THREAD

**Issue by JerryCaoZW** [wechat-python-sdk/wechat-python-sdk#56]
Hi, I am a beginner of python. When I use Send_message it raise NeedLoginError, then I put login before this function. But there is still a login error. My code shows as below. Could you please kindly help to fix it?

import json
from wechat_sdk import ext

loginname = 'j------4@gmail.com'
loginname = loginname.encode()
loginpwd = 'j-------i'
loginpwd = loginpwd.encode()

wechat = ext.WechatExt (username = loginname ,password= loginpwd)
wechat.login()

username = "someone"
username = username.encode()
content = "testing msg"
content = content.encode()
wechat.send_message(username, content)

Result:NeedLoginError: {"base_resp":{"ret":200002,"err_msg":"invalid args"}}

Thank you!

**Comment by doraemonext** [comment]
WechatExt 使用 fakeid 进行用户标识，您需要先取得该用户的 fakeid 后，然后将其作为第一个参数传入 send_message 方法。示例如下：

```
from wechat_sdk import WechatExt
ext = WechatExt('1422526@qq.com', '*************', login=False)
ext.login()
ext.send_message('oJNCEjt3uIphaC1DrpB030QxMV_w', 'test message')
```

fakeid 的获取请使用 get_message_list 方法。

**PS：因为微信官方公众平台的功能已经愈加完善，WechatExt已经没有继续维护的必要，v0.6.0版本已经停止了对其的更新，推荐您使用官方接口WechatBasic进行开发。**
