### ISSUE TITLE
jsapi_ticket既使填好了access_token依然显示41001错误

### ISSUE THREAD

**Issue by yalove** [wechat-python-sdk/wechat-python-sdk#58]
`conf = WechatConf(
			token='weixin',
			appid='wx0ec87cb12131239be97',
			appsecret='a4c6c140f7345bb32174a4e86581212',
			encrypt_mode='safe',
			encoding_aes_key='L6ITjVvks1X4Y0TUeQ2mcotZY0L1mFYW5lqxF2ZzYDp',
	    access_token='6Z8Yqhc1GTABYkBFUT4R1lSwwzf4RQ_HBrfXa8l3lhJ4nIrqOrycscxow5FFvm6_oyeOwNAyK3Hf4NfP0vM-VUTkABocLF0KwyWZYVOIVUV22UjWRF1P50cOsN_Kxpl8CUReAEAUMJ',
			access_token_expires_at=1454668255,)
conf.get_jsapi_ticket()
`
一直得到的是41001错误

**Comment by doraemonext** [comment]
非常感谢您提交的 Bug，当前已经修复，发布了v0.6.1版本，请执行 pip install --upgrade wechat_sdk 即可。
