### ISSUE TITLE
微信支付相关接口有没有计划开发？

### ISSUE THREAD

**Issue by bigzhu** [wechat-python-sdk/wechat-python-sdk#59]
比如[统一下单](https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_1)接口之类，似乎并没有开发

有没计划支持？

**Comment by doraemonext** [comment]
现在主要精力还在跟进mp.weixin.qq.com/wiki的接口，暂时还没有计划支持。

完成后将会考虑进行支持，谢谢您的关注 :smile:
