### ISSUE TITLE
对Python3的支持

### ISSUE THREAD

**Issue by mageelen** [wechat-python-sdk/wechat-python-sdk#60]
这个SDK只支持Python2吗？

**Comment by mageelen** [comment]
我发现没法import WechatBasic

**Comment by scuto** [comment]
@mageelen 同样无法`import WechatBasic`，你解决了吗
我是在sae上部署wechat_sdk的，环境为Python2.7，可以`import wechat_sdk`，无法`from wechat_sdk import WechatBasic`

**Comment by linzhanyu** [comment]
这个SDK无法安装到 Python3.x 上！

**Comment by hbrls** [comment]
@linzhanyu 装应该是可以的吧，用的时候偶尔有问题。你报什么错？

**Comment by sunzhaoyang** [comment]
没有办法import WechatBasic 是因为有些依赖包没有安装，而wechat_sdk 把异常都捕获掉了。可以修改wechat_sdk下的__init__.py ，把异常抛出来看，缺哪个模块安装就可以了。

我遇到的模块列表有：
six
xmltodict
Crypto
pycrypto

装完以后还要把Crypto重命名为小写crypto  = =!

但现在还是不能用的，因为basic.py里147行有个unicode，而python3里已经没有这货了...所以要改了才能用。

我已经放弃....重新回归2.7的怀抱

**Comment by jiajunhuang** [comment]
#69 在这个PR中有搞定在Python3中的导入问题~

不过我也是用到了才发现错误，其他的不兼容之处可能还要等我用到~

大家遇到Python3的问题也可以贴出来，我想我可以承担一部分port to python 3的工作-。-

**Comment by mgjnana** [comment]
我是来看亲同事的 - - @sunzhaoyang

**Comment by ZhangBohan** [comment]
@sunzhaoyang 还是说你挫

**Comment by zxh-str** [comment]
@sunzhaoyang  大神，求交往。

**Comment by sunzhaoyang** [comment]
你们仨.....

**Comment by doraemonext** [comment]
已经支持，谢谢大家 😄
