### ISSUE TITLE
有时候会出现UnicodeDecodeError

### ISSUE THREAD

**Issue by withshe** [wechat-python-sdk/wechat-python-sdk#67]
执行这句：wechat.parse_data(request.get_data())

request对象是flask提供的

大多数情况下都是正常的，但偶尔会看到日志里之行这一句会出现如下异常：

File "./app/weixin/views.py", line 65, in check
    wechat.parse_data(request.get_data())
  File "/usr/local/lib/python2.7/site-packages/wechat_sdk/basic.py", line 150, in parse_data
    data = data.encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 218: ordinal not in range(128)

请问我需要如何处理呢？谢谢。

**Comment by hbrls** [comment]
报错的文本是什么，能贴上来吗

**Comment by withshe** [comment]
非常抱歉，在出错的代码前面，没有打印原始的请求数据。我加上日志吧，再次出现这个错误时，再把原始请求数据贴上来。

**Comment by withshe** [comment]
request.get_data()打印的内容如下：
<xml><ToUserName><![CDATA[gh_77bef5e1510f]]></ToUserName>
<FromUserName><![CDATA[oE10Jty9qzQyj-_EtOXRGkNFpJ0U]]></FromUserName>
<CreateTime>1457505785</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[一]]></Content>
<MsgId>6259939680708565648</MsgId>
</xml>

我在公众号里，输入的中文“一”


打印上面的日志后，接着就之行这句：wechat.parse_data(request.get_data())

错误日志：
File "./app/weixin/views.py", line 66, in check
    wechat.parse_data(request.get_data())
  File "/usr/local/lib/python2.7/site-packages/wechat_sdk/basic.py", line 150, in parse_data
    data = data.encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 218: ordinal not in range(128)

**Comment by hbrls** [comment]
试试看这样的日志

    _logger.info(request.mimetype)
    _logger.info(request.headers)
    _logger.info(request.data)
    _logger.info(type(request.data))

**Comment by withshe** [comment]
下面是日志，谢谢

`
_logger.info(request.mimetype):
text/xml

_logger.info(request.headers):
/app/weixin/views.py:65} INFO - Cf-Ipcountry: CN
Cf-Ray: 2813489bcd321407-LAX
Content-Length: 276
User-Agent: Mozilla/4.0
Connection: Keep-Alive
Cf-Visitor: {"scheme":"https"}
Pragma: no-cache
Content-Type: text/xml
X-Forwarded-Proto: https
Host: our domain, for example www.baidu.com
Cf-Connecting-Ip: 101.*.*.59
Accept: */*
X-Forwarded-For: 101.*.*.59
Accept-Encoding: gzip

_logger.info(request.data):
<xml><ToUserName><![CDATA[gh_77bef5e1510f]]></ToUserName>
<FromUserName><![CDATA[oE10Jty9qzQyj-_EtOXRGkNFpJ0U]]></FromUserName>
<CreateTime>1457576385</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[一]]></Content>
<MsgId>6260242905399673683</MsgId>
</xml>

_logger.info(type(request.data)):
<type 'str'>
`

**Comment by withshe** [comment]
貌似这样可以解决问题，目前给公众号发英文、数字、中文都不会报错了

`wechat.parse_data(request.get_data().decode('utf-8'))`

**Comment by NikolaDi** [comment]
还是会出问题，我发送语音消息的时候会提示编码错误
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/website/wechat-IOT/main.py", line 34, in wechat_auth
    wechat.parse_data(request.data)
  File "/usr/local/lib/python2.7/dist-packages/wechat_sdk/basic.py", line 150, in parse_data
    data = data.encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 387: ordinal not in range(128)

**Comment by doraemonext** [comment]
已经在 develop 分支修复该问题，即将发布新版本。
