### ISSUE TITLE
被动回复空消息

### ISSUE THREAD

**Issue by liuwons** [wechat-python-sdk/wechat-python-sdk#76]
sdk里是不是没有提供被动回复空消息的函数？
官方文档：

>假如服务器无法保证在五秒内处理并回复，必须做出下述回复，这样微信服务器才不会对此作任何处理，并且不会发起重试（这种情况下，可以使用客服消息接口进行异步回复），否则，将出现严重的错误提示。详见下面说明：
> - 1、（推荐方式）直接回复success
> - 2、直接回复空串（指字节长度为0的空字符串，而不是XML结构体中content字段的内容为空）

**Comment by doraemonext** [comment]
已经Merge并发布新版本，谢谢 😄
