### ISSUE TITLE
pip无法正常安装模块

### ISSUE THREAD

**Issue by BroncoTc** [wechat-python-sdk/wechat-python-sdk#82]
readme.rst里有编码错误，在各种环境下均无法成功安装。当把setup中的长描述字段改为固定字符串时一切正常。

**Comment by Youngson** [comment]
安装时报以下错误： 
long_description=open("README.rst").read(),
 UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 2: illegal multibyte sequence

**Comment by jiajunhuang** [comment]
fixed: #85
