### ISSUE TITLE
多并发情况下如何正获取access_token

### ISSUE THREAD

**Issue by yarving** [wechat-python-sdk/wechat-python-sdk#86]
# 多并发情况下如何正确获取access_token
## 需求描述
我用Flask开发了个微信公众号，实现了个答题抽奖活动，需要验证答题者是否已经订阅，主要流程如下:
1. 通过网页授权获取用户访问CODE；
2. 通过access_token访问用户信息，获取用户open_id；
3. 通过用户open_id查询用户基本信息，主要获取是否已经订阅（此步骤需要access_token)。

>为了方便描述，以下wechat实例为wechat-python-sdk提供的WechatBasic对象。

## 问题描述
但是在access_token需要刷新时会碰到个问题：
由于Flask中我使用的wechat实例可能只能存活于一次session之中，所以每个用户的访问可能都会导致一次wechat实例初始化
> 证明过程是：我在wechat对象的构造函数中打印了log，每次网页请求都会打印一条log，所以证明了构造函数被调用

1. 一个用户进行访问，当获取用户用户基本信息时，刷新一次access_token
2. 另一个用户进行访问，又刷新一次access_token，导致第一个用户的wechat对象中存储的access_token失效
3. 所以在多并发情况下，导致第一个用户访问中的access_token已失效。

## 尝试解决方法
解决方法有两个：
1. 让wechat实例存活于flask整个生存期间，所有访问都共享一个wechat实例，但是这个我不知道做；
2. 我采用的方法是，为grant_access_token（刷新access_token的函数）写了一个回调函数，在每次初始化wechat实例刷新access_token时保存access_token和expire时间至数据库，在Flask中初始化wechat实例时从数据库中将access_token和expire时间作为构造函数入参传入。

### 第二个方法存在的缺陷
第二个方法也有问题，在access_token即将过期时，
1. 如果两个访问同时到达，则这两个处理都会进行access_token刷新操作，
2. 由于这两个操作是异步处理，并没有同步机制，如果先刷新的access_token后保存，则会将已经失效的access_token保存下来
3. 后来所有实例化wechat对象时所使用的access_token其实已经无效了。

> 在进行问题描述的时候我突然想到，可以在进行access_token保存时验证expire时间，如果expire时间比数据库中时间要晚，则说明这个access_token是后刷新的，予以保存，否则丢弃。

## 希望获得的帮助：
1. 是否又熟悉flask的大牛介绍下如何让flask中所有网页请求操作都共享一个wechat对象，也就是让wechat对象生存于flask服务的整个生命周期，并且所有网页请求中的wechat对象其实都是一个，也就是解决方法1；
2. 如何保证wechat对象在需要刷新access_token的操作中异步操作，因为我觉得wechat对象其实都是wechat class的副本，能不能在类中对实例化的对象的grant_access_token方法进行同步？

**Comment by doraemonext** [comment]
您好，请参见：[http://wechat-python-sdk.com/quickstart/wechatconf/#access_token](http://wechat-python-sdk.com/quickstart/wechatconf/#access_token)

**Comment by yarving** [comment]
@doraemonext 你好，多谢，通过access_token维护页面应该有用，能告知下WechatConf类定义在哪个文件下吗？我grep了一下没找到。

**Comment by doraemonext** [comment]
`from wechat_sdk import WechatConf`

`WechatConf` 在 wechat_sdk/core/conf.py 文件中

**Comment by doraemonext** [comment]
如果没有找到，请升级一下版本，最新版本：v0.6.3

**Comment by yarving** [comment]
@doraemonext 确实是版本的问题，pip现在还没提供v0.6.3。多谢，应该能够解决问题了，我再试试。

**Comment by doraemonext** [comment]
https://pypi.python.org/pypi/wechat-sdk

pip始终是最新版本，请确认安装命令是否正确：`pip install wechat-sdk`

如需升级，`pip install --upgrade wechat-sdk`
